Develop WD2 decoding
nu-ZOO/MULE pull request #10
Opened 2024-11-11 18:24 UTC by jwaiton

This PR introduces the functionality of processing into MULE, with multichannel decoding from *WaveDump 2* `.bin` files now being possible.

The data is stored in h5 files that will be defined by the user. I'm using this PR as a draft to develop the general structure of a pack such that the following ones will be easier to implement.

2024-11-11 18:24 UTC, jwaiton commented
Major additions that are still required:
- [ ] Add basic integration with executable, `proc.py` and the config files
- [ ] Refactor code significantly if possible

2024-11-14 10:42 UTC, jwaiton commented
I will also add some tools for reading the files quickly based on the chunking. Should these perhaps go in a differing section (analysis, core, etc)? @bpalmeiro

2024-11-19 16:30 UTC, jwaiton commented
I've added executable functionality, but now need to modify the tests to allow for this.

2024-11-21 17:51 UTC, jwaiton commented
pytest coverage at the moment:

```---------- coverage: platform linux, python 3.12.7-final-0 -----------
Name                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------
packs/acq/__init__.py                0      0   100%
packs/acq/acq.py                     6      0   100%
packs/core/__init__.py               0      0   100%
packs/core/core_utils.py             7      1    86%   14
packs/core/io.py                    31      0   100%
packs/proc/__init__.py               0      0   100%
packs/proc/proc.py                  18     10    44%   15-28
packs/proc/processing_utils.py     144     84    42%   66-114, 187-188, 205-206, 240-266, 321-324, 357-377, 439-484
packs/tests/processing_test.py      87      0   100%
packs/tests/setup_test.py           28      0   100%
packs/tests/temporal_test.py         2      0   100%
packs/tests/tests.py                 6      0   100%
packs/types/types.py                 9      0   100%
--------------------------------------------------------------
TOTAL                              338     95    72%
```

I'm not aiming for 100%, but I believe a few tests that are needed will help in increasing coverage:
test that the processing pack creates a file that matches what we expect, from start to finish.

2024-11-22 18:19 UTC, jwaiton commented
The new test explicitly attempts to utilise:
- chunking
- multiple channels

and tests them explicitly. The new coverage is:
![image](https://github.com/user-attachments/assets/dbc26611-cfed-4b74-96d9-2ccd87872541)

Of `processing_tests.py`:
240-266 is deprecated code I will remove
66-114 is WD1 code that will need to be refactored (raised here #11)

The other areas can and will be tested.

2024-11-22 19:16 UTC, jwaiton commented
Only sections no longer tests are WD1 related, or a specific line (#324 of `processing_utils.py`) that doesn't need testing (and may not be required anyway).

2024-11-25 16:41 UTC, jwaiton commented
There is a bug when running the decoder for singular channels that seems to select the channel number as the number of samples, causing the output for samples to be zero, and then refusing to write an empty table to the h5 file. Why this occurs I haven't fully checked, but the tests should catch this when creating the singular channel file via decoding. Will figure this out and patch

2025-01-31 17:15 UTC, jwaiton commented
Quite a significant bug has been found! Mathias and I were working and encountered a `MemoryError` in `process_header()`, this is caused by a single channel data file being read as a multi-channel data file (as intended). The issue arises with what values end up being assigned to the `channels` and `samples` values.

Channels was set to some number 10^10, which meant when trying to execute `file.read(4*samples*channels)` a memory error occurred.

The solution to this is being implemented now.

2025-02-12 09:18 UTC, bpalmeiro requested changes
I did a """"light"""" review, so probably missing things, but here you have my first round of comments

2025-02-12 09:18 UTC, bpalmeiro commented on packs/tests/processing_test.py
> +    assert len(x) == 0
shouldn't in this case at least a warning be raised?

2025-02-12 09:18 UTC, bpalmeiro commented on packs/tests/processing_test.py
> +def test_ensure_new_path_created():
missing the overwriting and the successful iteration tests

2025-02-12 10:57 UTC, jwaiton commented on packs/core/core_utils.py
> +    return [x for xs in xss for x in xs]
It's use case is in creating a structured numpy array [here](https://github.com/jwaiton/MULE/blob/include-WD2-processing/packs/proc/processing_utils.py#L290). I didn't want to mix non-structured with structured numpy arrays in case there is some casting peculiarities that I didn't understand.

For example, naively replacing `flatten(waveform)` with `np.array(waveform).flatten()` from the above link results in the data format being incorrect as expressed in this test-error:

`FAILED packs/tests/processing_test.py::test_formatting_works - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (82, 3, 3) + inhomogeneous part.`

I can take some time to replace this, but I think it will add a bit of complexity to an already quite ugly and unintuitive piece of code.

2025-02-12 10:57 UTC, jwaiton commented on packs/core/core_utils.py
> +    return [x for xs in xss for x in xs]
(Yes that means it should be refactored at some point)

2025-02-12 11:05 UTC, bpalmeiro commented on packs/core/core_utils.py
> +    return [x for xs in xss for x in xs]
Ok, let's write all future debt to pay and leave it as such for now

2025-02-12 11:10 UTC, jwaiton commented on packs/core/io.py
> +    return pd.DataFrame(list(map(list, h5_data)), columns = (types.event_info_type).names)
Appears to do so, and breaks no tests. Altering now

2025-02-12 12:07 UTC, jwaiton commented on packs/core/io.py
> +                h5_data.append(j)
For the datasets we're using at the moment the appending is fine, but I agree. We can specify the size of the arrays beforehand and assign the elements. This would take a little bit of time, so I'll open it as an issue.

2025-02-12 12:13 UTC, jwaiton commented on packs/proc/proc.py
> +
Added as issue (#19)

2025-02-12 12:14 UTC, jwaiton commented on packs/core/core_utils.py
> +    return [x for xs in xss for x in xs]
I can add it as an issue?

2025-02-12 12:16 UTC, jwaiton commented on packs/proc/proc.py
> +    # removing the first two components so that they can be fed into functions
The first two components are (in the processing case) `process` and `wavedump edition`, neither of which the function `process_bin_WD2` want to use. So they are always assumed (in the processing case) to be two arguments you don't want. This might have unintended problems in the future, but the tests should cover it if this condition breaks.

2025-02-12 12:16 UTC, jwaiton commented on packs/proc/proc.py
> +                raise RuntimeError(f"wavedump edition {conf_dict['wavedump_edition']} decoding isn't currently implemented.")
#16 is the PR on top of this one with WD1 functionality included

2025-02-12 12:18 UTC, jwaiton commented on packs/proc/processing_utils.py
> +        verbose     (bool)      :       Flag for outputting information
Explain this to me when you come back, im not sure I fully understand. :cat:

2025-02-12 12:23 UTC, jwaiton commented on packs/proc/processing_utils.py
> +
This code will be gone in #16, it was written a long time ago ([this](https://github.com/jwaiton/Wavedump_Wrapper_TPB/blob/master/Analyse/core/processing.py#L329) is where I took it from, but this itself was taken from elsewhere) and was passed through to ensure if Ted needed it he'd have a function to call.

2025-02-12 12:25 UTC, jwaiton commented on packs/proc/processing_utils.py
> +        directory = PATH[:-3] + "h5"
Because if the name has periods in it it might end up confused. This code is bad and will be removed in #16

2025-02-12 12:26 UTC, jwaiton commented on packs/proc/processing_utils.py
> +    return data
This function is being removed in #16, so no need for a new PR

2025-02-12 12:30 UTC, jwaiton commented on packs/proc/processing_utils.py
> +    sampling_period = int.from_bytes(file.read(8), byteorder=byte_order)
The different binary file output formats as described by CAEN in the wavedump 2 manual are as such:
![Screenshot from 2025-02-12 12-29-12](https://github.com/user-attachments/assets/b4a0b61a-96d1-4221-bd5d-8711ae69cca5)
We are considering the cases of `One file per Channel` and `Many channels per file` but not `Multi Board single file`. This can be added later if we plan to have many boards added at once, but for the timebeing; yes the size will stay the same.

2025-02-12 12:57 UTC, jwaiton commented on packs/proc/processing_utils.py
> +        byte_order (str)  :  Byte order
It is specified as optional in the arguments for the function, but I generally agree that they should have optional flags in the docstrings. Will add this as an issue (#20), as I think it perpetuates throughout all the functions (it's also in `read_binary()` just below this one).

2025-02-12 13:41 UTC, jwaiton commented on packs/proc/processing_utils.py
> +    if (event_number_1 -1 == event_number) and (samples_1 == samples) and sampling_period_1 == (sampling_period):
To pass the `if` statement on L209, you need to have a multiple channel file, which will pass the header processing correctly, meaning the second and first headers will be the same (except the event numbers will differ by one). Anything else is assumed to be a 1 channel file (the header breaks) and so it is processed differently.

2025-02-12 13:42 UTC, jwaiton commented on packs/proc/processing_utils.py
> +                                     and so should by default be set to zero if not chunking.
Now part of issue #20

2025-02-12 14:05 UTC, jwaiton commented on packs/proc/processing_utils.py
> +            if counter > 100:
I wrote it out as a for loop, but found it a bit more obtuse so kept it in this file loop. The breaking at 100 was just because I don't like completely unprotected while loops, although you can use walrus operators to avoid this, I found they were overly complex for what is quite a simple task.

2025-02-12 14:06 UTC, jwaiton commented on packs/proc/processing_utils.py
> +                    iterator   :  Optional[int] = 0) -> str:
Do you mean the value `iterator` isn't used?

2025-02-12 14:08 UTC, jwaiton commented on packs/proc/processing_utils.py
> +    return save_path
I think I left `iterator` in to be an alternative to the hard-coded value of 100, but realised the use-case for that was unrealistic. I've since removed it.

2025-02-12 14:10 UTC, jwaiton commented on packs/proc/processing_utils.py
> +
I'll add more info to the text, but this print should stay as it specifies where the data is going to be stored immediately after starting the processing pack.

2025-02-12 14:25 UTC, jwaiton commented on packs/proc/processing_utils.py
> +        while True:
Annoyingly, wavedump 1 and 2 doesn't give you the number of events at any point. So the only way to know you've run out of new events is to either read everything in at once, or keep checking for when the binary file ends up being empty. 

I'm trying to think of a better solution for the `while` loop atm, I guess the nicest way would be to determine the size of the binary based on one event, then figure out how many events are included by taking the total size and dividing it by this number. The process to do this in python isn't known to me yet, but I can start working on it.

2025-02-12 14:35 UTC, jwaiton commented on packs/proc/processing_utils.py
> +                save_data(event_info, rwf, save_path, counter)
Yes, but the chunking is within the h5 files, not for individual files as shown.
![image](https://github.com/user-attachments/assets/c79cb301-7aef-4512-895e-7f11a14d71bd)

2025-02-12 14:36 UTC, jwaiton commented on packs/types/types.py
> +        ])
Yes, it's a bit excessive but clear I think.

2025-02-12 15:12 UTC, jwaiton commented on packs/proc/processing_utils.py
> +    except:
I've made sure the except takes only the `MemoryError` as an input, so it will break if another (different) error pops up.

2025-02-12 15:13 UTC, jwaiton commented on packs/tests/processing_test.py
> +
We should, yes.

2025-02-12 15:14 UTC, bpalmeiro commented on packs/core/core_utils.py
> +    return [x for xs in xss for x in xs]
Be my guest!

2025-02-12 15:14 UTC, jwaiton commented on packs/tests/processing_test.py
> +    process_header(file)
I've altered this to expect a `UserWarning`, although I can make it more specific. I have also modified the `process_header()` function to break if the error is not that which we expect (MemoryError rather than channel-1 based error)

2025-02-12 15:14 UTC, bpalmeiro commented on packs/core/core_utils.py
> +    return [x for xs in xss for x in xs]
Maybe we can add an issue with technical debts?

2025-02-12 15:41 UTC, jwaiton commented on packs/tests/processing_test.py
> +    # but this may not always be the case.
This test is moreso a check to ensure that if the `len(x) == 0` case every stops being true, it is apparent. In reality this test should have a randomised number of channels and samples

2025-02-12 15:43 UTC, jwaiton commented on packs/tests/processing_test.py
> +def test_ensure_new_path_created():
what do you mean by successful iteration?

2025-02-12 15:56 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +
Finally something not addressed in #16 :P

2025-02-12 15:57 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +
As usual, I'm fine with this being technical debt, but poor student that has to pay it

2025-02-12 15:59 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +                    iterator   :  Optional[int] = 0) -> str:
yup

2025-02-12 16:00 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +    return save_path
you don't like the time stamp solution?

2025-02-12 16:00 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +
I mean more verbose print, not this going away, jic

2025-02-12 16:02 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +                save_data(event_info, rwf, save_path, counter)
So if you happen to have a massive one, you always have to copy full, while having chunked files can be sort of an advantage there

2025-02-12 16:03 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +                save_data(event_info, rwf, save_path, counter)
Again, as usual, not a very strong opinion, yous are the ones dealing with it all the time, so whatever is more comfortable for y'all

2025-02-12 16:07 UTC, jwaiton commented on packs/proc/processing_utils.py
> +    return save_path
I dont have any intuition on how long this should loop for before giving up, but 100 loops is instantaneous and always consistent. On the other hand, I think the logic should be altered given I find it highly likely that someone will want to add more than 100 files. I have no nice solution, but I don't really like using time to define it as one either.

2025-02-12 16:07 UTC, bpalmeiro commented on packs/tests/processing_test.py
> +
technical debt?

2025-02-12 16:07 UTC, bpalmeiro commented on packs/proc/processing_utils.py
> +    except:
Perfect, this is what I meant!

2025-02-12 16:09 UTC, jwaiton commented on packs/proc/processing_utils.py
> +                save_data(event_info, rwf, save_path, counter)
That's true, although if the files are that big the binary files should be separate before processing which eliminates the issue (you just run MULE multiple times with a script). I agree that adding it as functionality would be beneficial though.

2025-02-12 16:23 UTC, bpalmeiro commented on packs/tests/processing_test.py
> +    assert len(x) == 0
TD

2025-02-12 16:31 UTC, bpalmeiro commented on packs/tests/processing_test.py
> +def test_ensure_new_path_created():
The case you don't want to overwrite, and it loops and finds an available name

2025-02-18 18:32 UTC, bpalmeiro commented on packs/tests/processing_test.py
> +def test_ensure_new_path_created():
TD

2025-02-18 18:37 UTC, bpalmeiro approved these changes
I'm more or less satisfied with the addressing, although tonnes of things left to the future poor TD payer.

Good job!

2025-02-18 18:46 UTC, merged