Develop WD1 decoding
nu-ZOO/MULE pull request #16
Opened 2024-12-11 15:00 UTC by jwaiton

This PR introduces the functionality of processing into MULE, with single channel decoding from waveDump 1 `.dat` files now being possible.

The data is stored in h5 files with a storage path and name provided by the user. The h5 format matches that decoded in wavedump 2.

This PR rests on top of #10, and as such includes all the new bells and whistles. Config files, integration with the mule executable.

Things still needed
- [ ] tests
- [ ] refactor the code
- [ ] remove the deprecated function

2025-02-18 18:56 UTC, bpalmeiro approved these changes
not real hehe

2025-02-18 18:57 UTC, bpalmeiro requested changes
request

2025-03-18 15:31 UTC, jwaiton commented
Sorry for bloating PRs, but in this PR I'm including a smarter way to process data that is memory efficient. We now have a writer object that can writes individual waveforms to the h5 file.

I need to add forwards compatible functions for reading datasets lazily now, and allows for the selection of the 'group' and 'dataset' to be read. This is attached to #31.

2025-04-04 13:47 UTC, jwaiton commented
Test coverage now near 100%, although works on a 'whole function' basis, due to the reader, writers, and the decoder having limited compartmentalisation. Improved functionality would be nice, but currently it works as expected. I'd say its ready for a 'light' review, with the knowledge that almost every issue found will become technical debt :)

2025-04-22 09:20 UTC, jwaiton commented
I've split this PR up into two separate ones (#39 & #40), to help reviews flesh out more easily.

2025-04-22 09:20 UTC, closed without merging